INSERT INTO CLIENTE (NOMBRE, APELLIDOS, IDENTIFICACION, PAIS_RESIDENCIA, DIRECCION, TELEFONO, ESTADO) VALUES ('LUIS','GONZALEZ','401750695', 'CR' ,'MERCEDES NORTE', '88779087', true);
INSERT INTO CLIENTE (NOMBRE, APELLIDOS, IDENTIFICACION, PAIS_RESIDENCIA, DIRECCION, TELEFONO, ESTADO) VALUES ('CARLOS','MONTERO','341024120', 'CR' ,'MERCEDES SUR', '87451223', true);
INSERT INTO CLIENTE (NOMBRE, APELLIDOS, IDENTIFICACION, PAIS_RESIDENCIA, DIRECCION, TELEFONO, ESTADO) VALUES ('MIGUEL','SANCHEZ','102526236', 'USA' ,'FLORIDA', '1254131321', true);
INSERT INTO CLIENTE (NOMBRE, APELLIDOS, IDENTIFICACION, PAIS_RESIDENCIA, DIRECCION, TELEFONO, ESTADO) VALUES ('HORACIO','SALAZAR','0934555', 'EC' ,'QUITO', '84312131', true);
INSERT INTO CLIENTE (NOMBRE, APELLIDOS, IDENTIFICACION, PAIS_RESIDENCIA, DIRECCION, TELEFONO, ESTADO) VALUES ('ALBERTO','VIQUEZ','57651323', 'EC' ,'QUITO', '1531341', true);
